version: '3.2'

services:

#================================================================================================
# APACHE2
#================================================================================================
  apache2:
    restart: always
    build:
      context: .
      args:
        - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
        - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
        - DOCUMENT_ROOT=${CONFIG_APACHE}
    links:
      - workspace-phpfpm
    ports:
      - "${APACHE_HTTP_PORT}:80"
      - "${APACHE_HTTPS_PORT}:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${LOG_APACHE}:/var/log/apache2                          # volume for config
      - ${WORKSPACE}:/var/www/html                              # volume for data
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    environment:
      - APACHE_VERSION=${APACHE_VERSION}

#================================================================================================
# WORKSPACE PHP-FPM
#================================================================================================
  workspace-phpfpm:
    image: dockerframework/workspace-phpfpm:latest
    ports:
      - "${WORKSPACE_PHPFPM_PORT}:80"
      - "${WORKSPACE_XDEBUG_PORT}:9090"
    links:
      - ${DEFAULT_DATABASE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PHPFPM}:/usr/local/etc/php-fpm.conf                                # config path
      - ${CONFIG_PHPFPM_INI}:/usr/local/etc/php/php.ini                             # ini path
      - ${CONFIG_PHP_XDEBUG}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # xdebug config
      - ${LOG_PHPFPM}:/var/log/phpfpm                                               # log phpfpm
      - ${VENDOR_COMPOSER}:/usr/local/bin/composer                                  # vendor composer
      - ${VENDOR_DEPLOYER}:/usr/local/bin/dep                                       # vendor deployer
      - ${VENDOR_PHP_CS_FIXER}:/usr/local/bin/php-cs-fixer                          # vendor php-cs-fixer
      - ${WORKSPACE}:/var/www/html                                                  # volume for data
    environment:
      - NODE_VERSION=${NODE_VERSION}
      - YARN_VERSION=${YARN_VERSION}
